export const UnitBMSList = [

        {name: "SPEED_FB", unit:'Hz'},
        {name: "Auto_manual", unit:'Auto/Man'},
        {name: "BLOWER DP", unit:'Pa'},
        {name: "RA TEMP", unit:'°C'},
        {name: "RA RH", unit:'NMT 75%'},
        {name: "SA TEMP", unit:'°C'},
        {name: "MIX AIR TEMP", unit:'°C'},
        {name: "G4 FILTER DP", unit:'Pa'},
        {name: "F7 FILTER DP", unit:'Pa'},
        {name: "CHW IN TEMP", unit:'°C'},
        {name: "CHW OUT TEMP", unit:'°C'},
        {name: "HW IN TEMP", unit:'°C'},
        {name: "HW OUT TEMP", unit:'°C'},
        {name: "F9 FILTER DP", unit:'Pa'}
    
]
// export const dataBMSList = [
//     [
//         {name: "BMS.AHU39.VFDFrequency", val:'SPEED_FB'},
//         {name: "BMS.AHU39.Automanual", val:'Auto_manual'},
//         {name: "BMS.AHU39.AcrossBlowerDP", val:'BLOWER DP'},
//         {name: "BMS.AHU39.ReturnAirTemp", val:'RA TEMP'},
//         {name: "BMS.AHU39.ReturnAirRH", val:'RA RH'},
//         {name: "BMS.AHU39.SupplyAirTemp", val:'SA TEMP'},
//         {name: "BMS.AHU39.MixAirTemp", val:'MIX AIR TEMP'},
//         {name: "BMS.AHU39.G4Filter", val:'G4 FILTER DP'},
//         {name: "BMS.AHU39.F7Filter", val:'F7 FILTER DP'},
//         {name: "BMS.AHU39.ChilledWaterInTemp", val:'CHW IN TEMP'},
//         {name: "BMS.AHU39.ChilledWaterOutTemp", val:'CHW OUT TEMP'},
//         {name: "BMS.AHU39.HotWaterInTemp", val:'HW IN TEMP'},
//         {name: "BMS.AHU39.HotWaterOutTemp", val:'HW OUT TEMP'},
//         {name: "BMS.AHU39.F79Filter", val:'F9 FILTER DP'}
//     ],
//     [
//         {name: "BMS.AHU46.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU46.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU46.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU46.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU46.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU46.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU46.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU46.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU46.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU46.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU46.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU46.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU46.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU46.HotWaterOutTemp", id:'HW OUT TEMP'},
//     ],
//     [
//         {name: "BMS.AHU47.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU47.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU47.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU47.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU47.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU47.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU47.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU47.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU47.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU47.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU47.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU47.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU47.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU47.HotWaterOutTemp", id:'HW OUT TEMP'}        
//     ],
//     [
//         {name: "BMS.AHU49.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU49.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU49.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU49.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU49.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU49.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU49.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU49.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU49.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU49.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU49.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU49.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU49.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU49.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU40.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU40.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU40.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU40.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU40.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU40.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU40.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU40.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU40.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU40.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU40.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU40.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU40.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU40.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU41.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU41.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU41.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU41.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU41.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU41.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU41.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU41.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU41.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU41.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU41.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU41.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU41.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU41.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU42.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU42.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU42.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU42.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU42.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU42.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU42.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU42.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU42.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU42.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU42.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU42.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU42.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU42.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU44.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU44.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU44.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU44.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU44.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU44.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU44.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU44.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU44.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU44.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU44.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU44.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU44.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU44.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU50.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU50.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU50.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU50.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU50.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU50.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU50.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU50.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU50.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU50.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU50.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU50.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU50.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU50.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU43.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU43.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU43.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU43.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU43.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU43.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU43.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU43.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU43.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU43.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU43.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU43.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU43.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU43.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU45.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU45.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU45.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU45.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU45.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU45.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU45.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU45.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU45.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU45.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU45.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU45.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU45.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU45.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU48.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU48.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU48.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU48.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU48.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU48.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU48.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU48.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU48.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU48.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU48.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU48.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU48.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU48.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU55.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU55.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU55.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU55.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU55.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU55.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU55.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU55.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU55.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU55.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU55.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU55.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU55.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU55.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU56.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU56.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU56.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU56.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU56.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU56.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU56.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU56.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU56.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU56.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU56.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU56.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU56.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU56.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU57.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU57.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU57.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU57.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU57.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU57.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU57.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU57.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU57.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU57.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU57.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU57.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU57.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU57.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU58.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU58.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU58.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU58.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU58.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU58.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU58.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU58.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU58.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU58.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU58.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU58.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU58.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU58.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ],
//     [
//         {name: "BMS.AHU59.Automanual", id:'Auto_manual'},
//         {name: "BMS.AHU59.AcrossBlowerDP", id:'BLOWER DP'},
//         {name: "BMS.AHU59.VFDFrequency", id:'SPEED_FB'},
//         {name: "BMS.AHU59.ReturnAirTemp", id:'RA TEMP'},
//         {name: "BMS.AHU59.ReturnAirRH", id:'RA RH'},
//         {name: "BMS.AHU59.G4Filter", id:'G4 FILTER DP'},
//         {name: "BMS.AHU59.MixAirTemp", id:'MIX AIR TEMP'},
//         {name: "BMS.AHU59.SupplyAirTemp", id:'SA TEMP'},
//         {name: "BMS.AHU59.F7Filter", id:'F7 FILTER DP'},
//         {name: "BMS.AHU59.F79Filter", id:'F9 FILTER DP'},
//         {name: "BMS.AHU59.ChilledWaterInTemp", id:'CHW IN TEMP'},
//         {name: "BMS.AHU59.ChilledWaterOutTemp", id:'CHW OUT TEMP'},
//         {name: "BMS.AHU59.HotWaterInTemp", id:'HW IN TEMP'},
//         {name: "BMS.AHU59.HotWaterOutTemp", id:'HW OUT TEMP'}
//     ]
// ]