
export const REPORT_DATA_UPDATED = "REPORT_DATA_UPDATED";

export const SERIAL_NUMBER_UPDATED = "SERIAL_NUMBER_UPDATED";

export const BARCODE_NUMBER_UPDATED = "BARCODE_NUMBER_UPDATED";

export const STATION_SELECTION_UPDATED = "STATION_SELECTION_UPDATED";